---
- name: Provisionando dependências do projeto
  hosts: localhost
  become: false
  tasks:

    - name: Instalando dependências do docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Adicionando diretório Keyrings caso não exista
      ansible.builtin.file:
        name: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Adicionando chave gpg docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: Adicionado repositório apt
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalando docker
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Workaround for docker inside containers
      ansible.builtin.apt:
        cmd: sed -i 's/ulimit -Hn/ulimit -h/g' /etc/init.d/docker
